buyer/urls.py
from django.conf.urls import url


urlpatterns = [
    url(r'^register/$', 'buyer.views.register', name='register'),
    url(r'^(?P<username>\w+)/$', 'buyer.views.buyer_profile', name='buyer_profile'),
    url(r'^edit-profile/$', 'buyer.views.edit_buyer', name='edit_buyer'),
    url(r'^recent-design/$', 'buyer.views.my_recent_views', name='my_recent_views'),
    url(r'^favorite-design/$', 'buyer.views.my_favorites', name='my_favorites'),
   	url(r'^add-or-remove-favorite/$', 'buyer.views.add_or_remove_favorite',  name='add_or_remove_favorite'),
   	url(r'^add-to-cart/$', 'buyer.views.add_to_cart',  name='add_to_cart'),
    url(r'^delete-recently-viewed/$', 'buyer.views.delete_recent_views', name='delete_recent_views'),
    url(r'^create-feedback/$', 'buyer.views.create_feedback', name='create_feedback'),
    url(r'^my-cart/$', 'buyer.views.my_carts', name='my_carts'),
    url(r'^delete-cart-items/$', 'buyer.views.delete_cart_items', name='delete_cart_items'),
    url(r'^deliver-to/$', 'buyer.views.get_delivery_address', name='get_delivery_address'),
    url(r'^payement-method/$', 'buyer.views.get_payment_method', name='get_payment_method'),
    url(r'^my-orders/$', 'buyer.views.orders_list', name='orders_list'),
    url(r'^order-item/(?P<order_item_id>[0-9]+)/$', 'buyer.views.order_detail', name='order_detail'),
    url(r'^design-request/$', 'buyer.views.design_request', name='design_request'),
    url(r'^my-design-request/$', 'buyer.views.requested_design', name='requested_design'),

]

designer/urls.py
from django.conf.urls import url


urlpatterns = [
    url(r'^registration-designer/$', 'designer.views.registration', name='registration'),
    url(r'^(?P<username>\w+)/$', 'designer.views.profile', name='profile'),
    url(r'^edit-profile/$', 'designer.views.edit_designer', name='edit_designer'),
    url(r'^upload-design/$', 'designer.views.upload_design', name='upload_design'),
    url(r'^my-designs/$', 'designer.views.my_designs', name='my_designs'),
    url(r'^design-details/(?P<design_id>[0-9]+)/$', 'designer.views.design_details', name='design_details'),
    url(r'^delete-designs/$', 'designer.views.delete_design', name='delete_design'),
    url(r'^edit-designs/(?P<design_id>[0-9]+)/$', 'designer.views.edit_design', name='edit_design'),
    url(r'^get-dress-types/$', 'designer.views.get_dress_type', name='get_dress_type'),
    url(r'^design-request/$', 'designer.views.design_requests_designer', name='design_requests_designer'),
    url(r'^accept-reject-request/$', 'designer.views.accept_reject_request', name='accept_reject_request'),
]

fashion/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.contrib.auth import views
from django.views.static import serve
from django.conf import settings


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),

    # Home Url
    url(r'^$', 'designer.views.homepage', name='homepage'),
    url(r'^about-us/$', 'accounts.views.about_us', name='about_us'),
    url(r'^contact-us/$', 'accounts.views.contact_us', name='contact_us'),
    url(r'^newsletter/$', 'accounts.views.newsletter', name='newsletter'),
    url(r'^blog/$', 'accounts.views.blog', name='blog'),

    url(r'^design/design-detail/(?P<product_name>[\w-]+)/(?P<product_id>[0-9]+)/$', 'designer.views.product_details', name='product_details'),

    url(r'^all-designs/$', 'designer.views.fashion_home', name='fashion_home'),

    # App Url
    url(r'buyer/', include('buyer.urls')),
    url(r'designer/', include('designer.urls')),
    url(r'accounts/', include('accounts.urls')),

    # Logout Url
    url(r'^logout/$', views.logout, {'next_page': settings.LOGIN_REDIRECT_URL}, name="logout"),

    # Reset Password Url
    url(r'^user/password/reset/done/$',
        'django.contrib.auth.views.password_reset_done',
         name='password_reset_done'),

    # Media Url
    url(r'^media/(?P<path>.*)', serve, {"document_root": settings.MEDIA_ROOT})
]

designer/models.py
from __future__ import unicode_literals

import os
from datetime import datetime

from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django_countries.fields import CountryField
from django.core.files.storage import FileSystemStorage
from autoslug import AutoSlugField

from fashion.utils import SendEmail

media_storage = FileSystemStorage(location=settings.BASE_DIR, base_url="/media/")

GENDER_CHOICES = (
    ('Male', 'Male'),
    ('Female', 'Female'),
    ('Others', 'Others'),
)

CATEGORY_CHOICES = (
    ('Men', 'Men'),
    ('Women', 'Women'),
    ('Boys', 'Boys'),
    ('Girls', 'Girls')
)

PAYMENT_STATUS = (
    ('Pending', 'Pending'),
    ('Paid', 'Paid')
)

class Designer(models.Model):
    user = models.ForeignKey(User)
    avatar = models.ImageField(upload_to="profile/designer/", null=True, blank=True)
    phone_no = models.CharField(max_length=12, blank=True, null=True)
    gender = models.CharField(max_length=60, null=True, blank=True, choices=GENDER_CHOICES)
    street1 = models.CharField(max_length=60, blank=True, null=True)
    street2 = models.CharField(max_length=60, blank=True, null=True)
    city  = models.CharField(max_length=30, blank=True, null=True)
    state = models.CharField(max_length=30, blank=True, null=True)
    postal_code = models.CharField(max_length=12, blank=True, null=True)
    bio = models.TextField(null=True, blank=True)
    identity_document = models.FileField(upload_to="documents/identity/", null=True, blank=True)
    country = CountryField(blank_label="(select country)", null=True, blank=True)
    is_premium = models.BooleanField(default=False)

    def __str__(self):
        return u'%s %s' %(self.user.first_name, self.user.last_name)

    def get_identity_document(self):
        return os.path.basename(self.identity_document.name)


class Size(models.Model):
    slug = AutoSlugField(populate_from='name', unique=True)
    name = models.CharField(max_length=40)

    def __str__(self):
        return u'%s' %(self.name)


class DesignType(models.Model):
    slug = AutoSlugField(populate_from='types', unique=True)
    types = models.CharField(max_length=40)

    def __str__(self):
        return u'%s' %(self.types)


class Design(models.Model):
    avatar = models.ImageField(upload_to='design_images/', null=True, blank=True)
    avatar_1 = models.ImageField(upload_to='design_images/', null=True, blank=True)
    avatar_2 = models.ImageField(upload_to='design_images/', null=True, blank=True)
    avatar_3 = models.ImageField(upload_to='design_images/', null=True, blank=True)
    avatar_4 = models.ImageField(upload_to='design_images/', null=True, blank=True)
    avatar_5 = models.ImageField(upload_to='design_images/', null=True, blank=True)
    designer = models.ForeignKey(Designer)
    gender = models.CharField(max_length=60, choices=CATEGORY_CHOICES)
    design_type = models.ManyToManyField(DesignType)
    no_of_views = models.IntegerField(default=0, null=True, blank=True)
    name = models.CharField(max_length=255, blank=True, null=True)
    size = models.ManyToManyField(Size)
    details = models.TextField(null=True, blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    stock = models.BooleanField(default=True)
    design_rating = models.FloatField(default=0.0, null=True, blank=True)


    def __str__(self):
        return u'%s' % (self.name)


class FinancialActivities(models.Model):
    designer = models.ForeignKey(Designer)
    design = models.ForeignKey(Design)
    transfer_id = models.CharField(max_length=255, null=True, blank=True)
    status = models.CharField(max_length=60, choices=PAYMENT_STATUS)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return u'%s' % self.designer


def activate_account(sender, instance, **kwargs):
    if instance.id:
        old = instance.__class__.objects.get(id=instance.id)
        if not instance.is_active == old.is_active:
            user = User.objects.get(id=instance.id)
            password = user.password
            msg = SendEmail()
            msg.send(recipient=[user.email], template_path='email_messages/account_activated.html',
                context={
                    'user': user,
                },
                subject='Your Account has been activated successfully!'
            )

models.signals.pre_save.connect(activate_account, sender=User)

designer/forms.py
from __future__ import unicode_literals
from datetime import datetime

from django import forms
from django.conf import settings
from django.forms import FileInput
from django_countries import countries
from django.contrib.auth.models import User
from django.contrib.auth import password_validation
from designer.models import Designer, Design, Size, GENDER_CHOICES, CATEGORY_CHOICES


class SignUpDesignerForm(forms.Form):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    phone_no = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'maxlength': '15', 'minlength': '10'}))
    avatar = forms.ImageField(required=True)
    gender = forms.CharField(widget=forms.Select(choices=GENDER_CHOICES, attrs={'class': 'form-control'}))
    identity_document = forms.FileField(required=True)
    street1 = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'cols': '0', 'rows': '4'}), required=True)
    street2 =forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), required=False)
    city  = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), required=True)
    state = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), required=True)
    postal_code = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), required=True)
    country = forms.CharField(widget=forms.Select(choices=countries, attrs={'class': 'form-control'}), required=True)
    nationality = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), required=False)
    bio = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'cols': '0', 'rows': '0'}), required=False)        

    def clean_email(self):
        try:
            existing_user = User.objects.get(email__iexact=self.cleaned_data['email'])
            if existing_user:
                self._errors["email"] = self.error_class(["An account already exists under this email address. Please use the forgot password function to log in."])
        except User.MultipleObjectsReturned:
            self._errors["email"] = self.error_class(["An account already exists under this email address. Please use the forgot password function to log in."])
        except:
            pass

        return self.cleaned_data['email']

    def clean_phone_no(self):
        phone_no = self.cleaned_data.get('phone_no')

        try:
            phone_no = int(phone_no)
        except:
            raise forms.ValidationError('Enter a whole number.')

        return phone_no


class EditDesignerForm(forms.ModelForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(widget=forms.TextInput(attrs={'class': 'form-control', 'type': 'email', 'readonly': 'readonly'}))

    class Meta:
        model=Designer
        exclude = ['user', 'is_premium']
        widgets = {
            'avatar': FileInput(),
            'identity_document': FileInput(attrs={'style': 'padding-top: 15px'})
        }

    def __init__(self, *args, **kwargs):
        super(EditDesignerForm, self).__init__(*args, **kwargs)
        self.fields['phone_no'].widget.attrs.update({'class': 'form-control'})
        self.fields['street1'].widget.attrs.update({'class': 'form-control'})
        self.fields['street2'].widget.attrs.update({'class': 'form-control'})
        self.fields['city'].widget.attrs.update({'class': 'form-control'})
        self.fields['gender'].widget.attrs.update({'class': 'form-control'})
        self.fields['state'].widget.attrs.update({'class': 'form-control', 'cols': '', 'rows': ''})
        self.fields['postal_code'].widget.attrs.update({'class': 'form-control'})
        self.fields['country'].widget.attrs.update({'class': 'form-control'})
        self.fields['bio'].widget.attrs.update({'class': 'form-control', 'rows': '0', 'cols': '0', 'maxlength': '500'})
        self.fields['phone_no'].required = True
        self.fields['street1'].required = True
        self.fields['city'].required = True
        self.fields['state'].required = True


class UploadDesignForm(forms.Form):
    avatar = forms.ImageField(required=True)
    avatar_1 = forms.ImageField(required=True)
    avatar_2 = forms.ImageField(required=False)
    avatar_3 = forms.ImageField(required=False)
    avatar_4 = forms.ImageField(required=False)
    avatar_5 = forms.ImageField(required=False)
    design_type = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), required=True)
    gender = forms.CharField(widget=forms.Select(choices=CATEGORY_CHOICES, attrs={'class': 'form-control'}))
    name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'minlength': '4'}))
    size = forms.CharField(widget=forms.Select(attrs={'class': 'form-control multiselect mymultiselect', 'required': 'required'}))
    details = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'cols': '0', 'rows': '5'}), required=True)
    price = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Price'}))

    def __init__(self, *args, **kwargs):
        super(UploadDesignForm, self).__init__(*args, **kwargs)
        self.fields['size'] = forms.MultipleChoiceField(
            choices=[(size.id, str(size.name)) for size in Size.objects.all()]
        )
        self.fields['size'].required = True


    def clean_price(self):
        price = self.cleaned_data.get('price')

        try:
            price = float(price)
        except:
            raise forms.ValidationError('Enter a number.')

        return price


class EditDesignForm(forms.ModelForm):
    design_type = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), required=True)

    class Meta:
        model=Design
        exclude = ['designer', 'buyer', 'stock', 'no_of_views']
        widgets = {
            'avatar': FileInput(),
            'avatar_1': FileInput(),
            'avatar_2': FileInput(),
            'avatar_3': FileInput(),
            'avatar_4': FileInput(),
            'avatar_5': FileInput(),
        }

    def __init__(self, *args, **kwargs):
        super(EditDesignForm, self).__init__(*args, **kwargs)
        self.fields['avatar'].required = True
        self.fields['name'].widget.attrs.update({'class': 'form-control'})
        self.fields['gender'].widget.attrs.update({'class': 'form-control'})
        self.fields['price'].widget.attrs.update({'class': 'form-control'})
        self.fields['details'].widget.attrs.update({'class': 'form-control'})
        self.fields['size'] = forms.MultipleChoiceField(
            choices=[(size.id, str(size.name)) for size in Size.objects.all()]
        )
        self.fields['size'].required = True

    def clean_price(self):
        price = self.cleaned_data.get('price')

        try:
            price = float(price)
        except:
            raise forms.ValidationError('Enter a number.')

        return price

templates/designer/base_designer.html
{% load staticfiles %}

<div class="panel panel-default sidebar-menu">
    <div class="panel-heading">
        <h3 class="panel-title"><strong>&nbsp;&nbsp;&nbsp;My Accounts</strong></h3>
    </div>
    <div class="panel-body">
        <ul class="nav nav-pills nav-stacked">
            <li>
                <a href="{% url 'profile' request.user.username %}"><i class="fa fa-user"></i>Profile</a>
            </li>
            <li class="">
                <a href="{% url 'edit_designer' %}"><i class="fa fa-pencil"></i>Edit Profile</a>
            </li>
            <li>
                <a href="{% url 'change_password' %}"><i class="fa fa-lock"></i>Change Password</a>
            </li>
            <li>
                <a href="{% url 'upload_design' %}"><i class="fa fa-plus"></i>Upload Design</a>
            </li>
            <li>
                <a href="{% url 'design_requests_designer' %}"><i class="fa fa-bookmark" aria-hidden="true"></i>Design Request {% if request_counter > 0 %}<span class="badge" style="background-color: red;">{{request_counter}}{% endif %}</span></a>
            </li>
            <li class="{% if current == 'design_detail' %}active{% endif %}">
                <a href="{% url 'my_designs' %}"><i class="fa fa-list"></i>My Designs</a>
            </li>
            <li>
                <a href="{% url 'logout' %}"><i class="fa fa-sign-out"></i> Logout</a>
            </li>
        </ul>
    </div>
</div>

templates/designer/edit_profile.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
<style type="text/css">
    body{
        background-image: url({% static 'images/background_profile.jpg' %});
        background-repeat: no-repeat;
        background-attachment: fixed;
    }
</style> 
<div class="container">
    <div class="col-md-12">
        <ul class="breadcrumb profile-block" style="margin-top: -5px;">
            <li><a href="/">Home</a>
            </li>
            <li>Edit Profile</li>
        </ul>
    </div>
    <div class="col-md-3" style="margin-top: 10px">
        {% include "designer/base_designer.html" %}
    </div>
    <div class="col-md-9" style="margin-top: 10px;">
        <div class="box">
        	<div class="row">
	        	<div class="col-md-12" style="font-family: times">
                    <form id="signup_form" role="form" method="post" enctype="multipart/form-data" method="post">
                        {% csrf_token %}
                         <div class="row">
                            <div class="col-md-3">
                                <div class="form-group">
                                    <label for="id_avatar"><strong>Avatar</strong></label>
                                    <div id="id_avatar_img" style="cursor: pointer;" class="avatar_img">
                                        <img src="{% if designer.avatar %}{{ designer.avatar.url }}{% else %}{% static 'images/nodp.jpg' %}{% endif %}" alt="Cinque Terre">
                                    </div>
                                    {{ form.avatar }}
                                    <small class="es-error">{{ form.avatar.errors.as_text }}</small>
                                </div>
                            </div>
                        </div> 
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group {% if form.first_name.errors %}has-error{% endif %}">
                                    <label for="id_first_name"><strong>First Name</strong></label>
                                    {{ form.first_name }}
                                    <small class="es-error">{{ form.first_name.errors.as_text }}</small>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group {% if form.last_name.errors %}has-error{% endif %}">
                                    <label for="id_last_name"><strong>Last Name</strong></label>
                                    {{ form.last_name }}
                                    <small class="es-error">{{ form.last_name.errors.as_text }}</small>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group {% if form.email.errors %}has-error{% endif %}">
                                    <label for="id_email"><strong>Email</strong></label>
                                    {{ form.email }}
                                    <small class="es-error">{{ form.email.errors.as_text }}</small>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group {% if form.phone_no.errors %}has-error{% endif %}">
                                    <label for="id_phone_no"><strong>Phone No</strong></label>
                                    {{ form.phone_no }}
                                    <small class="es-error">{{ form.phone_no.errors.as_text }}</small>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group {% if form.bio.errors %}has-error{% endif %}">
                                    <label for="id_bio"><strong>Bio</strong></label>
                                    {{ form.bio }}
                                    <small class="es-error">{{ form.bio.errors.as_text }}</small>
                                </div>
                            </div>
                        </div> 
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group {% if form.street1.errors %}has-error{% endif %}">
                                    <label for="id_street1"><strong>Address</strong> </label>
                                    {{ form.street1 }}
                                    <small class="es-error">{{ form.street1.errors.as_text }}</small>
                                </div>
                            </div>
                        </div> 
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group {% if form.city.errors %}has-error{% endif %}">
                                    <label for="id_city"><strong>City</strong></label>
                                    {{ form.city }}
                                    <small class="es-error">{{ form.city.errors.as_text }}</small>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group {% if form.state.errors %}has-error{% endif %}">
                                    <label for="id_phone_no"><strong>State</strong></label>
                                    {{ form.state }}
                                    <small class="es-error">{{ form.state.errors.as_text }}</small>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group {% if form.postal_code.errors %}has-error{% endif %}">
                                    <label for="id_postal_code"><strong>Postal Code</strong></label>
                                    {{ form.postal_code }}
                                    <small class="es-error">{{ form.postal_code.errors.as_text }}</small>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group {% if form.country.errors %}has-error{% endif %}">
                                    <label for="id_country"><strong>Country</strong></label>
                                    {{ form.country }}
                                    <small class="es-error">{{ form.country.errors.as_text }}</small>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="id_identity_document"><strong>Identity Document</strong></label>
                                    {% if designer.identity_document %}
                                        <div id="id_display_identity_document">
                                            <a class="btn btn-md" title="Identity Document">
                                                <i class="fa fa-file-text" style="font-size:48px;color:red"></i>
                                                {{ designer.get_identity_document }}
                                            </a>
                                        </div>
                                    {% else %}
                                        {{ form.identity_document }}
                                    {% endif %}
    
                                    <small class="es-error">{{ form.identity_document.errors.as_text }}</small>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group {% if form.gender.errors %}has-error{% endif %}">
                                    <label for="id_phone_no"><strong>Gender</strong></label>
                                    {{ form.gender }}
                                    <small class="es-error">{{ form.gender.errors.as_text }}</small>
                                </div>
                            </div>
                        </div>     
                        <div>
                            <button type="submit" class="btn btn-primary"><i class="fa fa-user-md"></i>Update Profile</button>
                        </div>
                    </form>
	        	</div>
	        </div>	
        </div>
    </div>
</div>    

{% endblock %}

{% block javascript %}


    <script type="text/javascript">
        msg = "This field is required."

        $("#id_phone_no").keypress(function (e) {
            if (e.which != 8 && e.which != 0 && (e.which < 48 || e.which > 57)) {
                return false;
            }
        });
        
        $("#id_avatar").on('change', function () {
            var image_holder = $("#id_avatar_img");
            image_holder.empty();
            var reader = new FileReader();
            reader.onload = function (e) {
                $("<img />", {
                    "src": e.target.result
                }).appendTo(image_holder);

            }
            image_holder.show();
            $("#id_default_avatar").val("");

            $("#image_error").hide();
            reader.readAsDataURL($(this)[0].files[0]);
        });

        $("#id_avatar").css("display", "none");
        $("#id_avatar_img").on("click", function(){
            $("#id_avatar").trigger("click");
        });

        $('#id_avatar').change(function () {
            var ext = this.value.match(/\.(.+)$/)[1];
            switch (ext) {
                case 'jpg':
                case 'jpeg':
                case 'png':
                case 'gif':
                    $('#uploadButton').attr('disabled', false);
                    break;
                default:
                    alert('This is not an allowed file type.');
                    this.value = '';
                    location.reload();
            }
        });

    </script>

{% endblock %}

templates/designer/profile.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %} 
<style type="text/css">
    body{
        background-image: url({% static 'images/background_profile.jpg' %});
        background-repeat: no-repeat;
        background-attachment: fixed;
    }
</style> 

<div class="container">
    <div class="col-md-12">
        <ul class="breadcrumb profile-block" style="margin-top: -5px;">
            <li><a href="/">Home</a>
            </li>
            <li>Profile</li>
        </ul>
    </div>
    <div class="col-md-3" style="margin-top: 10px">
        {% include "designer/base_designer.html" %}
    </div>
    <div class="col-md-9" style="margin-top: 10px;">
        <div class="box">
        	<div class="row">
	        	<div class="col-md-3">
	        		<div class="profile-block">
	        			<img src="{% if designer.avatar %}{{ designer.avatar.url }}{% else %}{% static 'images/nodp.jpg' %}{% endif %}" height="200" width="140" style="border-radius: 5px;">
	        		</div>
	        	</div>
	        	<div class="col-md-9" style="font-family: times">
	        		<h2>About me<a href="{% url 'upload_design' %}"><button class="btn btn-primary btn-sm" style="float: right;"><i class="fa fa-plus"></i>Upload Design</button></a></h2>
	        		<hr style="margin-top: -12px; border-color: #02a9e7">
	        		<p style="text-align: justify; line-height: 20px; word-spacing: 5px;">{{ designer.bio }}</p>
	        	</div>
	        </div>	
        </div>
    </div>
</div>    

{% endblock %}