accounts/urls.py
from django.conf.urls import include, url

urlpatterns = [
    url(r'login/$', 'accounts.views.user_login', name='user_login'),
    url(r'^forget-password/$', 'accounts.views.forget_password', name='forget_password'),
    url(r'^reset-password/(?P<token>[a-zA-Z0-9]*)/$', 'accounts.views.user_reset_password', name="user_reset_password"),
    url(r'^change-password/$', 'accounts.views.change_password', name='change_password'),
    url(r'^newsletter/$', 'accounts.views.newsletter', name="newsletter")
]    

buyer/urls.py
from django.conf.urls import url


urlpatterns = [
    url(r'^register/$', 'buyer.views.register', name='register'),
    url(r'^(?P<username>\w+)/$', 'buyer.views.buyer_profile', name='buyer_profile'),
    url(r'^edit-profile/$', 'buyer.views.edit_buyer', name='edit_buyer'),
    url(r'^recent-design/$', 'buyer.views.my_recent_views', name='my_recent_views'),
    url(r'^favorite-design/$', 'buyer.views.my_favorites', name='my_favorites'),
   	url(r'^add-or-remove-favorite/$', 'buyer.views.add_or_remove_favorite',  name='add_or_remove_favorite'),
   	url(r'^add-to-cart/$', 'buyer.views.add_to_cart',  name='add_to_cart'),
    url(r'^delete-recently-viewed/$', 'buyer.views.delete_recent_views', name='delete_recent_views'),
    url(r'^create-feedback/$', 'buyer.views.create_feedback', name='create_feedback'),
    url(r'^my-cart/$', 'buyer.views.my_carts', name='my_carts'),
    url(r'^delete-cart-items/$', 'buyer.views.delete_cart_items', name='delete_cart_items'),
    url(r'^deliver-to/$', 'buyer.views.get_delivery_address', name='get_delivery_address'),
    url(r'^payement-method/$', 'buyer.views.get_payment_method', name='get_payment_method'),
    url(r'^my-orders/$', 'buyer.views.orders_list', name='orders_list'),
    url(r'^order-item/(?P<order_item_id>[0-9]+)/$', 'buyer.views.order_detail', name='order_detail'),
    url(r'^design-request/$', 'buyer.views.design_request', name='design_request'),
    url(r'^my-design-request/$', 'buyer.views.requested_design', name='requested_design'),

]

fashion/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.contrib.auth import views
from django.views.static import serve
from django.conf import settings


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),

    # Home Url
    url(r'^$', 'designer.views.homepage', name='homepage'),
    url(r'^about-us/$', 'accounts.views.about_us', name='about_us'),
    url(r'^contact-us/$', 'accounts.views.contact_us', name='contact_us'),
    url(r'^newsletter/$', 'accounts.views.newsletter', name='newsletter'),
    url(r'^blog/$', 'accounts.views.blog', name='blog'),

    url(r'^design/design-detail/(?P<product_name>[\w-]+)/(?P<product_id>[0-9]+)/$', 'designer.views.product_details', name='product_details'),

    url(r'^all-designs/$', 'designer.views.fashion_home', name='fashion_home'),

    # App Url
    url(r'buyer/', include('buyer.urls')),
    url(r'designer/', include('designer.urls')),
    url(r'accounts/', include('accounts.urls')),

    # Logout Url
    url(r'^logout/$', views.logout, {'next_page': settings.LOGIN_REDIRECT_URL}, name="logout"),

    # Reset Password Url
    url(r'^user/password/reset/done/$',
        'django.contrib.auth.views.password_reset_done',
         name='password_reset_done'),

    # Media Url
    url(r'^media/(?P<path>.*)', serve, {"document_root": settings.MEDIA_ROOT})
]

accounts/models.py
from django.db import models


class PasswordResetAuth(models.Model):
    email = models.EmailField(max_length=75)
    token = models.CharField(max_length=11)
    is_expired = models.BooleanField(default=False)

    def __str__(self):
        return u'%s' % self.email


class Newsletter(models.Model):
    email = models.EmailField(max_length=75)
    def __str__(self):
        return u'%s' % self.email

accounts/forms.py
from __future__ import unicode_literals

from django import forms
from django.contrib.auth.models import User
from django.contrib.auth import password_validation
from django.contrib.auth.forms import PasswordResetForm
from accounts.models import PasswordResetAuth


class LoginForm(forms.Form):
    email = forms.EmailField(max_length=75, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    def clean(self):
        cleaned_data = super(LoginForm, self).clean()
        email = cleaned_data.get("email", "")

        # user = User.objects.get(username=username)
        # if not user.password == cleaned_data["password"]:
        #     raise forms.ValidationError("Password is w")

        if not User.objects.filter(email=email).exists():
            raise forms.ValidationError("Account doesn't exist with this email id. Please try again!")
        else:
            user = User.objects.get(email=email)
            cleaned_data["username"] = user.username

        return cleaned_data


class PasswordChangeForm(forms.Form):
    old_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    new_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super(PasswordChangeForm, self).__init__(*args, **kwargs)

    def clean_old_password(self):
        """
        Validates that the old_password field is correct.
        """
        old_password = self.cleaned_data["old_password"]

        if not self.user.check_password(old_password):
            raise forms.ValidationError("Your old password was entered incorrectly. Please enter it again.")

        return old_password

    def clean_confirm_password(self):
        new_password = self.cleaned_data.get('new_password')
        confirm_password = self.cleaned_data.get('confirm_password')

        if new_password and confirm_password:
            if new_password != confirm_password:
                raise forms.ValidationError("The two password fields didn't match.")

        password_validation.validate_password(confirm_password, self.user)

        return confirm_password

    def save(self, commit=True):
        password = self.cleaned_data["new_password"]
        self.user.set_password(password)

        if commit:
            self.user.save()

        return self.user


class ForgetPasswordForm(forms.Form):
    email = forms.EmailField(max_length=75, widget=forms.TextInput(attrs={'class': 'form-control'}))

    def clean_email(self):
        cleaned_data = super(ForgetPasswordForm, self).clean()
        email = cleaned_data.get("email", "")
        if not User.objects.filter(email=email).exists():
            raise forms.ValidationError("Account doesn't exist with this email id. Please try again!")
        return email


class ResetPasswordForm(forms.Form):
    new_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    def __init__(self, *args, **kwargs):
        self.token = kwargs.pop('token', None)
        super(ResetPasswordForm, self).__init__(*args, **kwargs)

    def clean_confirm_password(self):
        cleaned_data = super(ResetPasswordForm, self).clean()
        new_password = cleaned_data.get("new_password", "")
        confirm_password = cleaned_data.get("confirm_password", "")

        if new_password != confirm_password:
            raise forms.ValidationError("Password did not match. Make it correct.")

        if not PasswordResetAuth.objects.filter(token=self.token, is_expired=False).exists():
            raise forms.ValidationError("Either you are not an identified user or token has been expired. So please click on forget password.")

        return confirm_password


class ContactForm(forms.Form):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'required': 'required'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'required': 'required'}))
    email = forms.EmailField(max_length=75, widget=forms.TextInput(attrs={'class': 'form-control', 'required': 'required'}))
    phone_no = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'required': 'required'}))
    message = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'cols': '0', 'rows': '8', 'required': 'required'}))


class NewsletterForm(forms.Form):
    email = forms.EmailField(widget=forms.TextInput(attrs={'type': 'text', 'class': 'form-control', 'placeholder': 'Email'}))

accounts/views.py
import json

from django.conf import settings
from django.shortcuts import render_to_response, redirect
from django.template import RequestContext
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.utils.crypto import get_random_string
from django.contrib.auth import update_session_auth_hash
from django.core.urlresolvers import reverse
from django.http import Http404, HttpResponse
from django.contrib import messages

from fashion.utils import SendEmail
from accounts.models import PasswordResetAuth, Newsletter
from accounts.forms import LoginForm, PasswordChangeForm, ForgetPasswordForm, ResetPasswordForm, ContactForm, NewsletterForm

from designer.models import Designer

def about_us(request):
    return render_to_response("about_us.html", {'current': 'about_us'}, context_instance=RequestContext(request))


def contact_us(request):
    contact_form = ContactForm(request.POST or None)

    if request.method == 'POST':
        if contact_form.is_valid():
            msg = SendEmail(request)
            msg.send(recipient=[settings.DEFAULT_CONTACT_EMAIL], template_path='email_messages/contact_us.html',
                context={
                    'first_name': contact_form.cleaned_data["first_name"],
                    'last_name': contact_form.cleaned_data["last_name"],
                    'phone_no': contact_form.cleaned_data["phone_no"],
                    'email': contact_form.cleaned_data["email"],
                    'message': contact_form.cleaned_data["message"]
                },
                subject='[Fashion Celio] {} sent a query!'.format(contact_form.cleaned_data["first_name"])
            )

            msg.send(recipient=[contact_form.cleaned_data["email"]], template_path='email_messages/contact_reply.html',
                    context={
                        'first_name': contact_form.cleaned_data["first_name"],
                    },
                    subject='Thank You for Contacting Us!'
                )
            messages.add_message(request, messages.INFO, "Thankyou for contacting us! We will get back to you shortly!".format(contact_form.cleaned_data["first_name"]))
            return redirect("/")

    return render_to_response("contact_us.html", {'current': 'contact_us', 'form': contact_form}, context_instance=RequestContext(request))


def newsletter(request):
    if request.method == 'POST' and request.is_ajax() and request.POST.get('email', ''):
        newsletter, _ = Newsletter.objects.get_or_create(email=request.POST.get('email', ''))

    return HttpResponse(json.dumps({'status': True}))


def user_login(request):

    if request.user.is_authenticated():
        return redirect("/")

    form = LoginForm(request.POST or None)

    if request.method == "POST":
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            user = authenticate(username=username, password=password)

            if user is not None:
                if user.is_active:
                    login(request, user)
                    if Designer.objects.filter(user=user).exists():
                        return redirect(request.GET.get("next", "/designer/%s/" % user.username))
                    else:
                        return redirect(request.GET.get("next", "/"))
                else:
                    error_message = "* This account is not activated yet, Please contact support for account activation!"
                    return render_to_response("accounts/login.html", {
                        "form": form,
                        "current": "login",
                        "error_message": error_message
                    }, context_instance=RequestContext(request))

            error_message = "* Email Id and password did not match. Please try again!"
            return render_to_response("accounts/login.html", {
                "form": form,
                "current": "login",
                "error_message": error_message
            }, context_instance=RequestContext(request))

        return render_to_response("accounts/login.html", {
            "form": form,
            "current": "login"
        }, context_instance=RequestContext(request))

    return render_to_response("accounts/login.html", {
        "form": form,
        "current": "login"
    }, context_instance=RequestContext(request))


@login_required
def change_password(request):
    form = PasswordChangeForm(request.user, request.POST or None)
    user = User.objects.get(id=request.user.id)

    if request.method == "POST":
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, user)
            messages.add_message(request, messages.INFO, "Hi {}, Your password has been changed successfully. Please login!".format(request.user.first_name))
            return redirect('/')
                
    return render_to_response("accounts/change_password.html", {
        "current": "reset_password",
        "form": form
    }, context_instance=RequestContext(request))


def forget_password(request):
    """
        Function is used for the forgot password functionality.
        In this password is resetted by sending a mail to registered users.
        Function also maintains a token for resetting the password which is later used to
        identify the user.
    """

    if request.user.is_authenticated():
        return redirect("/")

    form = ForgetPasswordForm(request.POST or None)

    if form.is_valid():
        email = form.cleaned_data["email"]
        token = get_random_string(length=11)
        PasswordResetAuth.objects.create(email=email, token=token)

        msg = SendEmail(request)
        msg.send(recipient=[email], template_path='email_messages/password_reset.html',
            context={
                'reset_link': settings.SITE_URL+"/accounts/reset-password/{}".format(token)
            },
            subject='Reset Password!'
        )

        return redirect(reverse('password_reset_done'))

    return render_to_response("accounts/user_identify.html", {
        "current": "forgot_password",
        "form": form
    }, context_instance=RequestContext(request))


def user_reset_password(request, token):
    """
        Function is used to reset the password of the user using the token identification
        which was created in forgot password.
    """

    if request.user.is_authenticated():
        return redirect("/")

    form = ResetPasswordForm(request.POST or None, token=token)

    try:
        password_reset_auth = PasswordResetAuth.objects.get(token=token, is_expired=False)
    except PasswordResetAuth.DoesNotExist:
        raise Http404

    if request.method == "POST":
        if form.is_valid():
            user = User.objects.get(email=password_reset_auth.email)
            new_password = form.cleaned_data["new_password"]
            user.set_password(new_password)
            user.save()

            password_reset_auth.is_expired = True
            password_reset_auth.save()
            return redirect(reverse('user_login'))

    return render_to_response("accounts/user_reset_password.html", {
        "current": "reset_password",
        "form": form
    }, context_instance=RequestContext(request))


def newsletter(request):
    """
    This function is used to subscribe the newsletter for the input email address.
    """
    response = {'status': False, 'errors': []}

    newsletterform = NewsletterForm(request.POST or None)

    if request.method == 'POST':
        if newsletterform.is_valid():
            Newsletter.objects.get_or_create(email=newsletterform.cleaned_data['email'])
            response['status'] = True

        else:
            for key, value in newsletterform.errors.iteritems():
                tmp = {'key': key, 'error': value.as_text()}
                response['errors'].append(tmp)

    return HttpResponse(json.dumps(response))


def blog(request):
    return render_to_response("blog.html", {
        
    }, context_instance=RequestContext(request)) 

templates/accounts/change_password.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %} 
<style type="text/css">
    body{
        background-image: url({% static 'images/background_profile.jpg' %});
        background-repeat: no-repeat;
        background-attachment: fixed;
    }
</style> 

<div class="container">
    <div class="col-md-12">
        <ul class="breadcrumb profile-block" style="margin-top: -5px;">
            <li><a href="/">Home</a>
            </li>
            <li>Change Password</li>
        </ul>
    </div>
    <div class="col-md-3" style="margin-top: 10px">
        <div class="panel panel-default sidebar-menu">
            <div class="panel-heading">
                <h3 class="panel-title"><strong>&nbsp;&nbsp;&nbsp;My Accounts</strong></h3>
            </div>
            <div class="panel-body">
                <ul class="nav nav-pills nav-stacked">
                    <li>
                        <a href="{% if role == 'designer' %}{% url 'profile' request.user.username %}{% else %}{% url 'buyer_profile' request.user.username %}{% endif %}"><i class="fa fa-user"></i>Profile</a>
                    </li>
                    <li>
                        <a href="{% if role == 'designer' %}{% url 'edit_designer' %}{% else %}{% url 'edit_buyer' %}{% endif %}"><i class="fa fa-pencil"></i>Edit Profile</a>
                    </li>
                    <li class="{% if  current == 'reset_password' %}active{% endif %}">
                        <a href="{% url 'change_password' %}"><i class="fa fa-lock"></i>Change Password</a>
                    </li>
                    {% if role == 'designer' %}
                        <li>
                            <a href="{% url 'upload_design' %}"><i class="fa fa-plus"></i>Upload Design</a>
                        </li>
                        <li>
                            <a href="{% url 'design_requests_designer' %}"><i class="fa fa-bookmark" aria-hidden="true"></i>Design Request</a>
                        </li>
                        <li>
                            <a href="{% url 'my_designs' %}"><i class="fa fa-list"></i>My Design</a>
                        </li>
                    {% else %}
                         <li>
                            <a href="{% url 'my_recent_views' %}"><i class="fa fa-eye"></i>Recently Viewed</a>
                        </li>
                        <li>
                            <a href="{% url 'my_favorites' %}"><i class="fa fa-heart" aria-hidden="true"></i>My Favorites Design</a>
                        </li>
                        <li>
                            <a href="{% url 'requested_design' %}"><i class="fa fa-bookmark" aria-hidden="true"></i>Design Request</a>
                        </li>
                    {% endif %}    
                    <li>
                        <a href="{% url 'logout' %}"><i class="fa fa-sign-out"></i> Logout</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-md-9" style="margin-top: 10px;">
        <div class="box">
        	<div class="row">
	        	<div class="col-md-12" style="font-family: times">
                    <form class="form-horizontal" id="chng_pass" method="post" data-toggle="validator" style="color: black; margin-top: 20px;">
                        {% csrf_token %}
                        <div class="form-group {% if form.old_password.errors %}has-error{% endif %}">
                            <div class="col-md-12">
                                <label for="id_old_password" class="control-label">Old Password:</label>
                                {{ form.old_password }}
                                <small class="es-error">{{ form.old_password.errors.as_text }}</small>
                            </div>
                        </div>
                        <div class="form-group {% if form.new_password.errors %}has-error{% endif %}">
                            <div class="col-md-12">
                                <label for="id_new_password" class="control-label">New Password:</label>
                                {{ form.new_password }}
                                <small class="es-error">{{ form.new_password.errors.as_text }}</small>
                            </div>
                        </div>
                        <div class="form-group {% if form.confirm_password.errors %}has-error{% endif %}">
                            <div class="col-md-12">
                                <label for="id_confirm_password" class="control-label">Confirm Password:</label>
                                {{ form.confirm_password }}
                                <small class="es-error">{{ form.confirm_password.errors.as_text }}</small>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-12">
                                <input class="btn btn-primary btn-md" type="submit" value="Change Password"/ style="width: 180px;">
                            </div>
                        </div>
                    </form>
	        	</div>
	        </div>	
        </div>
    </div>
</div>    

{% endblock %}

{% block javascript %}


{% endblock %}

templates/accounts/login.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
 <style type="text/css">
    body{
        background-image: url({% static 'images/background_regis.jpg' %});
        background-repeat: no-repeat;
        background-attachment: fixed;
    }
</style> 
<div class="container">
    <div class="col-md-6 col-md-offset-3">
        <div class="box">
            <div class="row">
                <form id="login_form" method="post" style="color: black; margin-top: 20px;">
                    {% csrf_token %}
                    {% if form.non_field_errors and not form.email.errors %}
                        <small class="es-error">{{ form.non_field_errors.as_text }}</small>
                    {% elif error_message %}
                        <small class="es-error">{{ error_message }}</small>
                    {% endif %}
                    <div class="form-group {% if form.email.errors %}has-error{% endif %}">
                        <div class="col-md-12">
                            <label for="id_email" class="control-label"><h5><strong>Email:</strong></h5></label>
                            {{ form.email }}
                            <small><div class="help-block with-errors"></div></small>
                            <small class="es-error">{{ form.email.errors.as_text }}</small>
                        </div>
                    </div>
                    <div class="form-group {% if form.password.errors %}has-error{% endif %}">
                        <div class="col-md-12">
                            <label for="id_password" class="control-label"><h5><strong>Password:</strong></h5></label>
                            {{ form.password }}
                            <small><div class="help-block with-errors"></div></small>
                            <small class="es-error">{{ form.password.errors.as_text }}</small>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-12">
                            <div class="clearfix">
                                <button type="submit" class="btn btn-primary"><i class="fa fa-sign-in"></i> Log in</button>
                                <a href="{% url 'forget_password' %}" style="float: right">Forgot Password ?</a>

                            </div>
                        </div>
                    </div>
                </form>
            </div> 
        </div>
    </div>    
</div>
{% endblock %}

templates/accounts/user_identify.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}Reset Password{% endblock %}


{% block content%}
     <style type="text/css">
        body{
            background-image: url({% static 'images/background_regis.jpg' %});
        }
    </style>
    <div class="container">
        <div class="col-md-6 col-md-offset-3">
            <div class="box"> 
                <div class="row">
                    <div class="col-md-12">
                        <h5>Forgot Password</h5>
                        <div class="text-subline"></div>
                    </div>
                </div>
                <form class="form-horizontal" id="user_iden" method="post" style="color: black; margin-top: 20px;">
                    {% csrf_token %}
                    <div class="form-group {% if form.email.errors %}has-error{% endif %}">
                        <div class="col-md-12">
                            <label for="id_email" class="control-label"><h5><strong>Email</strong></h5></label>
                            <input id="id_email" type="text" class="form-control" name="email" placeholder="Email" aria-describedby="basic-addon1">
                            <small><div class="help-block with-errors"></div></small>
                            <small class="es-error">{{ form.email.errors.as_text }}</small>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-12">
                            <div class="clearfix">
                                <input class="btn btn-primary btn-md" type="submit" value="Reset Password"/>
                                <div class="pull-right" style="margin-top: 20px;">
                                    <a href="{% url 'user_login' %}"><strong>Login</strong></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>            
                  
{% endblock %}

{% block javascript %}
    
   
   
{% endblock %}

templates/accounts/user_reset_password.html
{% extends "base.html" %}

{% block title %}Reset Password{% endblock %}
{% load staticfiles %}


{% block content %}
   
 <div class="container">
    <div class="col-md-6 col-md-offset-3">
        <div class="box"> 
            <form id="res_pass" class="form-horizontal" method="post" style="color: black; ">
                {% csrf_token %}
                
                <div class="form-group {% if form.new_password.errors %}has-error{% endif %}">
                    <div class="col-md-12">
                        <label for="id_new_password" class="control-label"><h5><strong>New Password:</strong></h5></label>
                        {{ form.new_password }}
                        <small class="es-error">{{ form.new_password.errors.as_text }}</small>
                    </div>
                </div>
                <div class="form-group {% if form.confirm_password.errors %}has-error{% endif %}">
                    <div class="col-md-12">
                        <label for="id_confirm_password" class="control-label"><h5><strong>Confirm Password:</strong></h5></label>
                        {{ form.confirm_password }}
                        <small class="es-error">{{ form.confirm_password.errors.as_text }}</small>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-12">
                        <div class="clearfix">
                            <div>
                                <input class="btn btn-primary btn-md" type="submit" value="Reset Password"/>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>    

                  
    
   
{% endblock %}

{% block javascript %}

{% endblock %}