buyer/urls.py
from django.conf.urls import url


urlpatterns = [
    url(r'^register/$', 'buyer.views.register', name='register'),
    url(r'^(?P<username>\w+)/$', 'buyer.views.buyer_profile', name='buyer_profile'),
    url(r'^edit-profile/$', 'buyer.views.edit_buyer', name='edit_buyer'),
    url(r'^recent-design/$', 'buyer.views.my_recent_views', name='my_recent_views'),
    url(r'^favorite-design/$', 'buyer.views.my_favorites', name='my_favorites'),
   	url(r'^add-or-remove-favorite/$', 'buyer.views.add_or_remove_favorite',  name='add_or_remove_favorite'),
   	url(r'^add-to-cart/$', 'buyer.views.add_to_cart',  name='add_to_cart'),
    url(r'^delete-recently-viewed/$', 'buyer.views.delete_recent_views', name='delete_recent_views'),
    url(r'^create-feedback/$', 'buyer.views.create_feedback', name='create_feedback'),
    url(r'^my-cart/$', 'buyer.views.my_carts', name='my_carts'),
    url(r'^delete-cart-items/$', 'buyer.views.delete_cart_items', name='delete_cart_items'),
    url(r'^deliver-to/$', 'buyer.views.get_delivery_address', name='get_delivery_address'),
    url(r'^payement-method/$', 'buyer.views.get_payment_method', name='get_payment_method'),
    url(r'^my-orders/$', 'buyer.views.orders_list', name='orders_list'),
    url(r'^order-item/(?P<order_item_id>[0-9]+)/$', 'buyer.views.order_detail', name='order_detail'),
    url(r'^design-request/$', 'buyer.views.design_request', name='design_request'),
    url(r'^my-design-request/$', 'buyer.views.requested_design', name='requested_design'),

]

fashion/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.contrib.auth import views
from django.views.static import serve
from django.conf import settings


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),

    # Home Url
    url(r'^$', 'designer.views.homepage', name='homepage'),
    url(r'^about-us/$', 'accounts.views.about_us', name='about_us'),
    url(r'^contact-us/$', 'accounts.views.contact_us', name='contact_us'),
    url(r'^newsletter/$', 'accounts.views.newsletter', name='newsletter'),
    url(r'^blog/$', 'accounts.views.blog', name='blog'),

    url(r'^design/design-detail/(?P<product_name>[\w-]+)/(?P<product_id>[0-9]+)/$', 'designer.views.product_details', name='product_details'),

    url(r'^all-designs/$', 'designer.views.fashion_home', name='fashion_home'),

    # App Url
    url(r'buyer/', include('buyer.urls')),
    url(r'designer/', include('designer.urls')),
    url(r'accounts/', include('accounts.urls')),

    # Logout Url
    url(r'^logout/$', views.logout, {'next_page': settings.LOGIN_REDIRECT_URL}, name="logout"),

    # Reset Password Url
    url(r'^user/password/reset/done/$',
        'django.contrib.auth.views.password_reset_done',
         name='password_reset_done'),

    # Media Url
    url(r'^media/(?P<path>.*)', serve, {"document_root": settings.MEDIA_ROOT})
]

buyer/models.py
from __future__ import unicode_literals

import os
from datetime import datetime

from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django_countries.fields import CountryField
from django.core.files.storage import FileSystemStorage
from autoslug import AutoSlugField
from designer.models import Design, Size, Designer

media_storage = FileSystemStorage(location=settings.BASE_DIR, base_url="/media/")


GENDER_CHOICES = (
    ('Male', 'Male'),
    ('Female', 'Female'),
    ('Others', 'Others'),
)

ORDER_ITEM_STATUS = (
    ('Requested', 'Requested'),
    ('OutForDelivery', 'OutForDelivery'),
    ('Delivered', 'Delivered')
)

ORDER_STATUS = (
    ('Draft', 'Draft'),
    ('Success', 'Success'),
    ('Canceled', 'Canceled'),
    ('Failed', 'Failed')            
)

PAYMENT_CHOICE = (
    ('COD', 'COD'),
    ('ONLINE', 'ONLINE')
)

DESIGN_REQUEST_STATUS = (
    ('Pending', 'Pending'),
    ('Accepted', 'Accepted'),
    ('Rejected', 'Rejected')
)

class Buyer(models.Model):
    user = models.ForeignKey(User)
    avatar = models.ImageField(upload_to="profile/buyer/", null=True, blank=True)
    phone_no = models.CharField(max_length=12, blank=True, null=True)
    gender = models.CharField(max_length=60, null=True, blank=True, choices=GENDER_CHOICES)
    address = models.TextField(null=True, blank=True)
    city  = models.CharField(max_length=30, blank=True, null=True)
    state = models.CharField(max_length=30, blank=True, null=True)
    postal_code = models.CharField(max_length=12, blank=True, null=True)
    country = CountryField(blank_label="(select country)", null=True, blank=True)
    favorite_design = models.ManyToManyField(Design)

    def __str__(self):
        return u'%s %s' %(self.user.first_name, self.user.last_name)


class RecentlyViewed(models.Model):
    design = models.ForeignKey(Design)
    user = models.ForeignKey(User)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)


class CartItems(models.Model):
    design = models.ForeignKey(Design)
    size = models.ForeignKey(Size)
    buyer = models.ForeignKey(Buyer)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)


class Feedback(models.Model):
    buyer = models.ForeignKey(Buyer)
    design = models.ForeignKey(Design)
    title = models.CharField(max_length=50, blank=True, null=True)
    rating = models.FloatField(default=0.0)
    reviews = models.TextField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    modified = models.DateTimeField(auto_now=True, null=True, blank=True)
    is_public = models.BooleanField(default=True)


class Order(models.Model):
    buyer = models.ForeignKey(Buyer, null=True, blank=True)
    first_name = models.CharField(max_length=100, null=True, blank=True)
    last_name = models.CharField(max_length=100, null=True, blank=True)
    phone_no = models.CharField(max_length=10, null=True, blank=True)
    city = models.CharField(max_length=100, null=True, blank=True)
    address = models.TextField(null=True, blank=True)
    state = models.CharField(max_length=100, null=True, blank=True)
    postal_code = models.CharField(max_length=12, blank=True, null=True)
    country = models.CharField(max_length=255, null=True, blank=True)
    order_time = models.DateTimeField(auto_now_add=True)
    total_price = models.DecimalField(max_digits=18, decimal_places=2)
    order_status = models.CharField(max_length=30, choices=ORDER_STATUS, null=True, blank=True)
    payement_method = models.CharField(max_length=30, choices=PAYMENT_CHOICE, null=True, blank=True)
    charge_id = models.CharField(max_length=100, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    def __unicode__(self):
        return u'Order by %s' % self.buyer


class OrderItem(models.Model):  
    order = models.ForeignKey(Order)
    buyer = models.ForeignKey(Buyer, null=True, blank=True)
    design = models.ForeignKey(Design, on_delete=models.PROTECT)
    size = models.ForeignKey(Size, null=True, blank=True)
    unit_price = models.DecimalField(max_digits=18, decimal_places=2)
    created = models.DateTimeField(auto_now_add=True, null=True, blank=True) 
    order_item_status = models.CharField(max_length=30, choices=ORDER_ITEM_STATUS, default='Requested')
    delivery_day = models.CharField(max_length=50, null=True, blank=True)

    def __unicode__(self):
        return u'%s- %s' % (self.design, self.order)


class DesignRequest(models.Model):
    title = models.CharField(max_length=255)
    size = models.ManyToManyField(Size)
    description = models.TextField(null=True, blank=True)
    design_image = models.ImageField(upload_to="request_design/designs/", null=True, blank=True)
    buyer = models.ForeignKey(Buyer)
    designer = models.ForeignKey(Designer)
    request_status = models.CharField(max_length=30, choices=DESIGN_REQUEST_STATUS, default='Pending')
    reject_reason = models.TextField(null=True, blank=True)
    price = models.DecimalField(max_digits=18, decimal_places=2)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

buyer/forms.py
from __future__ import unicode_literals
from datetime import datetime

from django import forms
from django.conf import settings
from django.forms import FileInput
from django_countries import countries
from django.contrib.auth.models import User
from django.contrib.auth import password_validation
from buyer.models import Buyer, GENDER_CHOICES, Feedback
from designer.models import Designer, Size


class SignUpBuyerForm(forms.Form):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    def clean_email(self):
        try:
            existing_user = User.objects.get(email__iexact=self.cleaned_data['email'])
            if existing_user:
                self._errors["email"] = self.error_class(["An account already exists under this email address. Please use the forgot password function to log in."])
        except User.MultipleObjectsReturned:
            self._errors["email"] = self.error_class(["An account already exists under this email address. Please use the forgot password function to log in."])
        except:
            pass

        return self.cleaned_data['email']


class EditBuyerForm(forms.ModelForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(widget=forms.TextInput(attrs={'class': 'form-control', 'type': 'email', 'readonly': 'readonly'}))

    class Meta:
        model=Buyer
        exclude = ['user', 'favorite_design']
        widgets = {
            'avatar': FileInput(),
        }

    def __init__(self, *args, **kwargs):
        super(EditBuyerForm, self).__init__(*args, **kwargs)
        self.fields['phone_no'].widget.attrs.update({'class': 'form-control'})
        self.fields['address'].widget.attrs.update({'class': 'form-control', 'cols': '', 'rows': '3'})
        self.fields['city'].widget.attrs.update({'class': 'form-control'})
        self.fields['gender'].widget.attrs.update({'class': 'form-control'})
        self.fields['state'].widget.attrs.update({'class': 'form-control'})
        self.fields['postal_code'].widget.attrs.update({'class': 'form-control'})
        self.fields['country'].widget.attrs.update({'class': 'form-control'})


class FeedbackForm(forms.Form):
    title = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    rating = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    reviews = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'rows': '4'}))


class DesignRequestForm(forms.Form):
    title = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control  myinputclass', 'placeholder': 'Give Title of the Design', 'maxlength': '100'}))
    size = forms.CharField(widget=forms.Select(attrs={'class': 'form-control multiselect mymultiselect', 'required': 'required'}))
    description = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control myinputclass', 'rows': 5, 'placeholder': 'Describe Your Design', 'maxlength': '1000'}))
    design_image = forms.ImageField(required=True)
    designer = forms.ChoiceField(widget=forms.Select(attrs={'class': 'form-control myinputclass'}))
    price = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Price'}))

    def clean_price(self):
        price = self.cleaned_data.get('price')

        try:
            price = float(price)
        except:
            raise forms.ValidationError('Enter a number.')

        return price


    def __init__(self, *args, **kwargs):
        super(DesignRequestForm, self).__init__(*args, **kwargs)
        self.fields['designer'] = forms.ChoiceField(
            choices=[(str(designer.id), str(designer.user.get_full_name())) for designer in Designer.objects.all()]
        )
        self.fields['size'] = forms.MultipleChoiceField(
            choices=[(size.id, str(size.name)) for size in Size.objects.all()]
        )
        self.fields['size'].required = True
        self.fields['designer'].widget.attrs.update({'class': 'form-control'})
        self.fields['designer'].required = True

templates/buyer/design_request.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %} 
<style type="text/css">
    @media screen and (min-width: 991px) {
        .multiselect{
            min-height: 44px;
            min-width: 470px;
        }
    }
</style>

<div class="container">
    <form id="signup_form" role="form" method="post" enctype="multipart/form-data" method="post">
        {% csrf_token %}
        <div class="box">
            <div class="row">
                <div class="col-md-5">
                    <div class="form-group">
                        <div id="id_avatar_img" style="cursor: pointer;" class="design_img" style="height: 400px;">
                            <img src="{% static 'images/blank_design.jpg' %}" alt="Cinque Terre">
                        </div>
                        {{ form.design_image }}
                        <small class="es-error">{{ form.design_image.errors.as_text }}</small>
                    </div>
                </div>
                <div class="col-md-5">
                    <div class="row">
                        <div class="form-group">
                            <div class="{% if form.title.errors %}has-error{% endif %}">
                                <label for="id_title"><strong>Title</strong></label>
                                {{ form.title }}
                                <small class="es-error">{{ form.title.errors.as_text }}</small>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group">
                            <div class="{% if form.size.errors %}has-error{% endif %}">
                                <label for="id_title"><strong>Size</strong></label><br>
                                {{ form.size }}
                                <small class="es-error">{{ form.size.errors.as_text }}</small>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group">
                            <div class="{% if form.description.errors %}has-error{% endif %}">
                                <label for="id_description"><strong>Description</strong></label>
                                {{ form.description }}
                                <small class="es-error">{{ form.description.errors.as_text }}</small>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group">
                            <div class="{% if form.designer.errors %}has-error{% endif %}">
                                <label for="id_designer"><strong>Select Designer</strong></label>
                                {{ form.designer }}
                                <small class="es-error">{{ form.designer.errors.as_text }}</small>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group">
                            <div class="{% if form.price.errors %}has-error{% endif %}">
                                <label for="id_price"><strong>Price</strong></label>
                                {{ form.price }}
                                <small class="es-error">{{ form.price.errors.as_text }}</small>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-offset-8 col-md-2">
                    <input type="submit" class="btn btn-primary" id="uploadButton" value="Submit" style="float: right;">
                </div>    
            </div>
        </div>
    </form>
</div>    

{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/bootstrap-multiselect.css' %}" type="text/css"/>
{% endblock %}

{% block javascript %}
    <script src="{% static 'js/bootstrap-multiselect.js' %}"></script>

    <script type="text/javascript">
        $(document).ready(function() {
            $('#id_size').multiselect();
            $("#id_size").on('change',function(e){
                if( $(this).val() !== null ){
                    $("#id_size").closest('.form-group').removeClass('has-error');
                    $("#id_size").closest('.form-group').find('.es-error').hide();
                }else{
                    $("#id_size").closest('.form-group').addClass('has-error');
                    $("#id_size").closest('.form-group').find('.es-error').show();
                }
                
            });
       
        });

        $("#id_price").keypress(function (e) {
            if (e.which != 8 && e.which != 0 && (e.which < 48 || e.which > 57)) {
                return false;
            }
        });
        
        $("#id_design_image").on('change', function () {
            var image_holder = $("#id_avatar_img");
            image_holder.empty();
            var reader = new FileReader();
            reader.onload = function (e) {
                $("<img />", {
                    "src": e.target.result
                }).appendTo(image_holder);

            }
            image_holder.show();
            $("#id_default_avatar").val("");

            $("#image_error").hide();
            reader.readAsDataURL($(this)[0].files[0]);
        });

        $("#id_design_image").css("display", "none");
        $("#id_avatar_img").on("click", function(){
            $("#id_design_image").trigger("click");
        });
        $('#id_design_image').change(function () {
            var ext = this.value.match(/\.(.+)$/)[1];
            switch (ext) {
                case 'jpg':
                case 'jpeg':
                case 'png':
                case 'gif':
                    $('#uploadButton').attr('disabled', false);
                    break;
                default:
                    alert('This is not an allowed file type.');
                    this.value = '';
                    location.reload();
            }
        });
    </script>

{% endblock %}

templates/buyer/edit_profile.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
<style type="text/css">
    body{
        background-image: url({% static 'images/background_profile.jpg' %});
        background-repeat: no-repeat;
        background-attachment: fixed;
    }
</style> 
<div class="container">
    <div class="col-md-12">
        <ul class="breadcrumb profile-block" style="margin-top: -5px;">
            <li><a href="/">Home</a>
            </li>
            <li>Edit Profile</li>
        </ul>
    </div>
    <div class="col-md-3" style="margin-top: 10px">
        {% include "buyer/base_buyer.html" %}
    </div>
    <div class="col-md-9" style="margin-top: 10px;">
        <div class="box">
        	<div class="row">
	        	<div class="col-md-12" style="font-family: times">
                    <form id="signup_form" role="form" method="post" enctype="multipart/form-data" method="post">
                        {% csrf_token %}
                         <div class="row">
                            <div class="col-md-3">
                                <div class="form-group">
                                    <label for="id_avatar"><strong>Avatar</strong></label>
                                    <div id="id_avatar_img" style="cursor: pointer;" class="avatar_img">
                                        <img src="{% if buyer.avatar %}{{ buyer.avatar.url }}{% else %}{% static 'images/nodp.jpg' %}{% endif %}" alt="Cinque Terre">
                                    </div>
                                    {{ form.avatar }}
                                    <small class="es-error">{{ form.avatar.errors.as_text }}</small>
                                </div>
                            </div>
                        </div> 
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group {% if form.first_name.errors %}has-error{% endif %}">
                                    <label for="id_first_name"><strong>First Name</strong></label>
                                    {{ form.first_name }}
                                    <small class="es-error">{{ form.first_name.errors.as_text }}</small>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group {% if form.last_name.errors %}has-error{% endif %}">
                                    <label for="id_last_name"><strong>Last Name</strong></label>
                                    {{ form.last_name }}
                                    <small class="es-error">{{ form.last_name.errors.as_text }}</small>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group {% if form.email.errors %}has-error{% endif %}">
                                    <label for="id_email"><strong>Email</strong></label>
                                    {{ form.email }}
                                    <small class="es-error">{{ form.email.errors.as_text }}</small>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group {% if form.phone_no.errors %}has-error{% endif %}">
                                    <label for="id_phone_no"><strong>Phone No</strong></label>
                                    {{ form.phone_no }}
                                    <small class="es-error">{{ form.phone_no.errors.as_text }}</small>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group {% if form.street1.errors %}has-error{% endif %}">
                                    <label for="id_address"><strong>Address</strong> </label>
                                    {{ form.address }}
                                    <small class="es-error">{{ form.address.errors.as_text }}</small>
                                </div>
                            </div>
                        </div> 
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group {% if form.city.errors %}has-error{% endif %}">
                                    <label for="id_city"><strong>City</strong></label>
                                    {{ form.city }}
                                    <small class="es-error">{{ form.city.errors.as_text }}</small>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group {% if form.state.errors %}has-error{% endif %}">
                                    <label for="id_phone_no"><strong>State</strong></label>
                                    {{ form.state }}
                                    <small class="es-error">{{ form.state.errors.as_text }}</small>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group {% if form.postal_code.errors %}has-error{% endif %}">
                                    <label for="id_postal_code"><strong>Postal Code</strong></label>
                                    {{ form.postal_code }}
                                    <small class="es-error">{{ form.postal_code.errors.as_text }}</small>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group {% if form.country.errors %}has-error{% endif %}">
                                    <label for="id_country"><strong>Country</strong></label>
                                    {{ form.country }}
                                    <small class="es-error">{{ form.country.errors.as_text }}</small>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group {% if form.gender.errors %}has-error{% endif %}">
                                    <label for="id_phone_no"><strong>Gender</strong></label>
                                    {{ form.gender }}
                                    <small class="es-error">{{ form.gender.errors.as_text }}</small>
                                </div>
                            </div>
                        </div>     
                        <div>
                            <button type="submit" class="btn btn-primary"><i class="fa fa-user-md"></i>Update Profile</button>
                        </div>
                    </form>
	        	</div>
	        </div>	
        </div>
    </div>
</div>    

{% endblock %}

{% block javascript %}


    <script type="text/javascript">
        msg = "This field is required."

        $("#id_phone_no").keypress(function (e) {
            if (e.which != 8 && e.which != 0 && (e.which < 48 || e.which > 57)) {
                return false;
            }
        });
        
        $("#id_avatar").on('change', function () {
            var image_holder = $("#id_avatar_img");
            image_holder.empty();
            var reader = new FileReader();
            reader.onload = function (e) {
                $("<img />", {
                    "src": e.target.result
                }).appendTo(image_holder);

            }
            image_holder.show();
            $("#id_default_avatar").val("");

            $("#image_error").hide();
            reader.readAsDataURL($(this)[0].files[0]);
        });

        $("#id_avatar").css("display", "none");
        $("#id_avatar_img").on("click", function(){
            $("#id_avatar").trigger("click");
        });
        $('#id_avatar').change(function () {
            var ext = this.value.match(/\.(.+)$/)[1];
            switch (ext) {
                case 'jpg':
                case 'jpeg':
                case 'png':
                case 'gif':
                    $('#uploadButton').attr('disabled', false);
                    break;
                default:
                    alert('This is not an allowed file type.');
                    this.value = '';
                    location.reload();
            }
        });

    </script>

{% endblock %}

templates/buyer/registration.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %} 
    <style type="text/css">
        body{
            background-image: url({% static 'images/background_regis.jpg' %});
            background-repeat: no-repeat;
            background-attachment: fixed;
        }
    </style> 
    <div class="container">
        <div class="col-md-6 col-md-offset-3">
            <div class="box">
                <form id="signup_form" role="form" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group {% if form.first_name.errors %}has-error{% endif %}">
                                <label for="id_first_name"><strong>First Name</strong></label>
                                {{ form.first_name }}
                                <small class="es-error">{{ form.first_name.errors.as_text }}</small>
                            </div>
                        </div>
                    </div>
                    <div class="row">    
                        <div class="col-md-12">
                            <div class="form-group {% if form.last_name.errors %}has-error{% endif %}">
                                <label for="id_last_name"><strong>Last Name</strong></label>
                                {{ form.last_name }}
                                <small class="es-error">{{ form.last_name.errors.as_text }}</small>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group {% if form.email.errors %}has-error{% endif %}">
                                <label for="id_email"><strong>Email</strong></label>
                                {{ form.email }}
                                <small class="es-error">{{ form.email.errors.as_text }}</small>
                            </div>
                        </div>
                    </div>
                    <div class="row">    
                        <div class="col-md-12">
                            <div class="form-group {% if form.password.errors %}has-error{% endif %}">
                                <label for="id_password"><strong>Password</strong> </label>
                                {{ form.password }}
                                <small class="es-error">{{ form.password.errors.as_text }}</small>
                            </div>
                        </div>
                    </div>    
                    <div>
                        <button type="submit" class="btn btn-primary"><i class="fa fa-user-md"></i> Register</button>
                    </div>
                </form>
            </div>
        </div>
    </div> 
    
{% endblock %}

{% block javascript %}


    <script type="text/javascript">

    </script>

{% endblock %}